### ISSUE TITLE
Support Java 12 exceptionallyCompose

### ISSUE THREAD

**Issue by bcluap** [smallrye/smallrye-context-propagation#223]
Context propagation should work across exceptionallyCompose:

This is a simple reproducer:

    @Inject
    HttpServletRequest httpRequest;
    @Inject
    ThreadContext threadContext;

    @GET
    @Path("/test")
    @Produces(MediaType.TEXT_PLAIN)
    public CompletionStage<String> test() {
        log.warn("A [{}]", httpRequest.getMethod());

        CompletableFuture<String> cf = CompletableFuture.completedFuture("Hello");

        cf = cf.thenApplyAsync((String s) -> {
            try {
                Thread.sleep(10);
            } catch (Exception e) {
            }
            return s + ".";
        });

        cf = threadContext.withContextCapture(cf);

        return cf
                .thenApply((String s) -> {
                    log.warn("B [{}]", httpRequest.getMethod());
                    return s + ".";
                })
                .exceptionally((Throwable t) -> {
                    return "Failed";
                })
                .thenApply((String s) -> {
                    log.warn("C [{}]", httpRequest.getMethod());
                    return s + ".";
                })
                .exceptionallyCompose((Throwable t) -> {
                    log.warn("Got here");
                    return CompletableFuture.completedStage("Failed");
                })
                .thenApply((String s) -> {
                    log.warn("I am here");
                    try {
                        log.warn("D [{}]", httpRequest.getMethod());
                    } catch (javax.enterprise.context.ContextNotActiveException e) {
                        log.warn("Error:", e);
                    }
                    return s + ".";
                });
    }

The logs:

2020-10-26 16:43:48,229 WARN  [gur.jin.ser.ser.res.ScenariosResource] (executor-thread-199) A [GET]
2020-10-26 16:43:48,239 WARN  [gur.jin.ser.ser.res.ScenariosResource] (ForkJoinPool.commonPool-worker-21) B [GET]
2020-10-26 16:43:48,239 WARN  [gur.jin.ser.ser.res.ScenariosResource] (ForkJoinPool.commonPool-worker-21) C [GET]
2020-10-26 16:43:48,239 WARN  [gur.jin.ser.ser.res.ScenariosResource] (ForkJoinPool.commonPool-worker-21) I am here
2020-10-26 16:43:48,240 WARN  [gur.jin.ser.ser.res.ScenariosResource] (ForkJoinPool.commonPool-worker-21) Error:: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
at io.quarkus.undertow.runtime.ServletProducer_ProducerMethod_request_eaedc3e40b2e72a682c41b95c654df6e208065d2_ClientProxy.arc$delegate(ServletProducer_ProducerMethod_request_eaedc3e40b2e72a682c41b95c654df6e208065d2_ClientProxy.zig:69)
at io.quarkus.undertow.runtime.ServletProducer_ProducerMethod_request_eaedc3e40b2e72a682c41b95c654df6e208065d2_ClientProxy.getMethod(ServletProducer_ProducerMethod_request_eaedc3e40b2e72a682c41b95c654df6e208065d2_ClientProxy.zig:251)
at guru.jini.services.servicename.rest.ScenariosResource.lambda$test$5(ScenariosResource.java:174)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
at io.smallrye.context.CompletableFutureWrapper.lambda$new$0(CompletableFutureWrapper.java:34)

As you can see, using exceptionallyCompose causes the context to disappear from then on in the chain (even though there is no exception). If I remove the exceptionallyCompose then  log.warn("D [{}]", httpRequest.getMethod()); works fine. .exceptionally does not face this problem and the context passes it just fine.

I came across this scenario in some code where we want to deal with an exception and compose it with a non blocking reactive call which looks at the original request context. This reproducer code creates the same issue.

**Comment by bcluap** [comment]
The PR covers the new Java 12 methods but build fails as it runs with Java 11. Not sure what the best approach is for this
